// #ifndef HAVAC_CONSTANTS_H
// #define HAVAC_CONSTANTS_H

// #define NUM_CELL_GROUPS 16
// #define CELLS_PER_GROUP 16
// #define SEQUENCE_SEGMENT_LENGTH NUM_CELL_GROUPS * CELLS_PER_GROUP

// #define SOFT_SSV_SEQUENCE_LENGTH 256
// #define SOFT_SSV_PHMM_LENGTH 256

// #endif
